name: Create docs

on:
  push:
    branches: [docs]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install
      - run: yarn run docs

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'docs --force'
          branch: docs
          message: 'docs\: New docs'
